### PR TITLE
Docusaurus Docs Page

### PR DESCRIPTION
**Pull request by ndom91**
Hey @marcan, big fan of the project! :rocket: 

I noticed there was nothing in this docs repo yet, and seeing as I'm a web developer, I decided to throw together a quick Docusaurus (docs framework based on React - https://v2.docusaurus.io) based page.

You can check it out here for now: https://asahilinux.netlify.app/

Of course we can change any of the colors, logos, etc. once you have some more of that stuff decided upon. I just put some place holder content / images in there for now.

If you want to add actual documentation, its simply a matter of editing/adding markdown files in the `docs/` subdirectory and editing the `sidebars.js` file to display links to the new pages.

### CODE REVIEW

**Comment by marcan** [comment]
Hi! This repo is actually intended to serve as a wiki container currently, see the PD docs in the wiki section (sorry, hadn't gotten around to adding a README explaining this yet). We'll probably have "proper" docs here at some point, but right now a wiki format is best since things will move very quickly at this stage of the project.

**Comment by ndom91** [comment]
Ah gotcha. Well this is basically the same, except just markdown files in the `/doc` directory. But if you want to stick with the github one that makes sense too. Let me know if theres anything else I can do this early on!

**Comment by marcan** [comment]
The main thing about the wiki is that anyone can edit it (as of a few hours ago), and that it all uses the web interface; this kind of workflow is more useful for collaborative jotting down of notes than a proper git one (I know there's a web editor for the main git too, but it's heavier weight and aimed for a different use case). I'll close this for now, we can revisit it later if it starts making sense to formalize the docs.

Once I have the stack for the main project website worked out though, I'm sure you can help out improving the templates and look for that :) right now I'm leaning towards Hugo on GitHub pages for the backend.

**Comment by ndom91** [comment]
Sounds good! I've used mkdocs as well for a wiki based site (also a python based static site generator type thing) which was really nice. They have a super popular and featureful material design wiki theme. 

Anyway, keep up the great work. I'll keep my eyes and ears peeled to patreon emails, etc. when the time comes :wink:

**Pull request closed without merging**
